---
language: python
python: "2.7"
sudo: required

env:
  - TESTDIR=/tmp/ansible-test

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y curl

install:
  # Install Ansible.
  - pip install ansible

script:
  # Run the role/playbook with ansible-playbook.
  - "chmod +x ./test.sh"
  - "./test.sh"
